module.exports = {
  globals: {},
  rules: {
    // code styles (warnings)
    "semi": 1,
    "prefer-spread": 1,
    "indent": [1, 2],
    "arrow-spacing": [1, {"before": true, "after": true}],
    "comma-spacing": [1, {"before": false, "after": true}],
    "key-spacing": [1, {"beforeColon": false, "afterColon": true}],
    "max-statements-per-line": [1, {"max": 1}],
    "array-bracket-spacing": [1, "always"],
    "object-curly-spacing": [1, "always"],
    "operator-linebreak": [1, "none"],
    "linebreak-style": [1, "unix"],
    "quotes": [1, "single"],
    // Problems (error)
    "func-names": [2, "never"],
    "prefer-arrow-callback": 2,
    "no-use-before-define": 2,
    "no-unreachable-loop": 2,
    "no-floating-decimal": 2,
    "dot-notation": 2,
    "no-empty-function": 2,
    "func-style": ["error", "expression"],
    "vars-on-top": 2,
    "no-var": 2,
    // Webperf additions
    "no-eval": "error",
    "no-implied-eval": "error",
    "no-new-func": "error",
    "no-script-url": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-prototype-builtins": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-unmodified-loop-condition": "error",
    "no-unused-expressions": "error",
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "require-await": "error",
    "no-return-await": "error",
    "eqeqeq": ["error", "always"],
    "no-console": "warn",
    "no-undef": "error",
    "no-unused-vars": ["error", {
      vars: "all",
      args: "after-used",
      ignoreRestSiblings: false,
    }],
    semi: "off",
    quotes: "off",
    indent: "off",
    "comma-dangle": "off",
    "space-before-function-paren": "off",
  }
};